### ISSUE TITLE
Errors preforming boolean operations with extruded svg

### ISSUE THREAD

**Issue by calob-dev** [jscad/scad-api#26]
I am attempting to preform a difference operation on a CSG cube with an extruded svg image. In this example, I am simply trying to remove a small disk from the surface of a block, using an svg.

Here is the script I am attempting to execute:
```

const scad = require('@jscad/scad-api');
const stlSerializer = require('@jscad/stl-serializer').serialize;
const svgDeSerializer = require('@jscad/svg-deserializer').deserialize;

const { cube } = scad.primitives3d;
const { difference } = scad.booleanOps;
const { center } = scad.transformations;
const { linear_extrude } = scad.extrusions;

// Text Engraving
let csgImage = svgDeSerializer("<svg height=\100\" width=\"100\"><circle cx=\"50\" cy=\"50\" r=\"40\" stroke=\"black\" stroke-width=\"3\" fill=\"red\" /> </svg>", null, {output: 'csg'});

//The Actual Construct
let block = cube({ size: [20, 20, 5]}).center('x', 'y');
let engraving = linear_extrude({height: .5}, csgImage).center('x', 'y');

let output = difference(block, engraving);

//Output Construct as STL
let raw = stlSerializer(output);
let stl = Buffer.concat([Buffer.from(raw[0]), Buffer.from(raw[1]), Buffer.from(raw[2])]);

process.stdout.write(stl);
```

Here is the error output from Node.JS:
```
[calob@asgard the-squire]$ node engrave-test.js > engraving_text.stl
/home/calob/Projects/BattlePrints/product-models/node_modules/@jscad/csg/csg.js:3216
                    var splitresult = plane.splitPolygon(polygon);
                                            ^

TypeError: plane.splitPolygon is not a function
    at CSG.PolygonTreeNode._splitByPlane (/home/calob/Projects/BattlePrints/product-models/node_modules/@jscad/csg/csg.js:3216:45)
    at CSG.PolygonTreeNode.splitByPlane (/home/calob/Projects/BattlePrints/product-models/node_modules/@jscad/csg/csg.js:3198:22)
    at CSG.Node.addPolygonTreeNodes (/home/calob/Projects/BattlePrints/product-models/node_modules/@jscad/csg/csg.js:3444:41)
    at CSG.Tree.addPolygons (/home/calob/Projects/BattlePrints/product-models/node_modules/@jscad/csg/csg.js:3331:27)
    at new CSG.Tree (/home/calob/Projects/BattlePrints/product-models/node_modules/@jscad/csg/csg.js:3304:28)
    at CSG.subtractSub (/home/calob/Projects/BattlePrints/product-models/node_modules/@jscad/csg/csg.js:334:21)
    at CSG.subtract (/home/calob/Projects/BattlePrints/product-models/node_modules/@jscad/csg/csg.js:327:33)
    at difference (/home/calob/Projects/BattlePrints/product-models/node_modules/@jscad/scad-api/src/ops-booleans.js:42:13)
    at Object.<anonymous> (/home/calob/Projects/BattlePrints/product-models/the-squire/engrave-test.js:17:14)
    at Module._compile (module.js:612:30)
```

It appears that somewhere between calling the boolean operator and spliting the PolygonNodeTree, something besides the CSG.Plane object is passed as the first agrument to _splitByPlane.

I honestly don't have enough experience with these libraries, or the math behind them, to hunt the error on my own.

Any ideas?

-----------------------------------------------

As an aside: if you call the operator with the extruded svg object as the first argument, and the standard CSG.Cube second, it works just fine.  If attempting a union, this is fine, but as I am trying to engrave svg images into the CSG.Cube, there isn't a work around for this that I can see.

**Comment by z3dev** [comment]
@CalobHumble thanks for using the libraries.

I don't see anything wrong with your script. You can call difference(CSG,CSG) or CSG.subtract(CSG). 
The outcome should be the same.

I'll try the same script this evening. @kaosat-dev might have some suggestions as well.

**Comment by z3dev** [comment]
Quick question... are you using the latest IO libraries for SVG?

**Comment by calob-dev** [comment]
@z3dev it seems I'm using @jscad/io version 0.3.5 from npm

**Comment by calob-dev** [comment]
Update:  I have deleted and reinstalled the libraries directly from npm. The original problem with the subtract operator seems to be resolved, however a new issue has occured:

```
[calob@asgard tests]$ node engrave-test.js > test.stl
/home/calob/Projects/BattlePrints/product-models/node_modules/@jscad/csg/src/CSG.js:1189
            delete sidestocheck[sidetag]
                                ^

ReferenceError: sidetag is not defined
    at CSG.fixTJunctions (/home/calob/Projects/BattlePrints/product-models/node_modules/@jscad/csg/src/CSG.js:1189:33)
    at transform (/home/calob/Projects/BattlePrints/product-models/node_modules/@jscad/io-utils/ensureManifoldness.js:11:46)
    at ensureManifoldness (/home/calob/Projects/BattlePrints/product-models/node_modules/@jscad/io-utils/ensureManifoldness.js:15:40)
    at serialize (/home/calob/Projects/BattlePrints/product-models/node_modules/@jscad/stl-serializer/index.js:13:10)
    at Object.<anonymous> (/home/calob/Projects/BattlePrints/product-models/tests/engrave-test.js:20:11)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
```




My dependicies list:
```
    "@jscad/csg": "^0.3.1",
    "@jscad/io": "^0.3.5",
    "@jscad/openjscad": "^1.0.3",
    "@jscad/scad-api": "^0.3.5",
    "@jscad/stl-serializer": "0.0.5",
    "@jscad/svg-deserializer": "^0.2.1",
```


I will investigate further, and see if I can resolve the issue myself, but any assistance is greatly appreciated.

**Comment by calob-dev** [comment]
I have temporarily solved the issue by rolling back the stl-serializer library to 0.0.4.

**Comment by kaosat-dev** [comment]
Hi @CalobHumble , thanks for the report !
I'll try to reproduce the error. 
Is your script above the complete script ?

**Comment by kaosat-dev** [comment]
Actually I was able to reproduce the error straight away, I will work on a fix asap

**Comment by kaosat-dev** [comment]
interestingly enough if output is set to either just `engraving` or `block` there are no issues, so the output of difference is wrong somehow.
The error you are getting is very likely related to the very recent (yesterday) addition of a function that ensures manifoldness of the stl ouput via `fixTJunctions`

**Comment by kaosat-dev** [comment]
ok so after digging into the issue further , it turns out that `fixTJunctions` itself is broken , so I will have to patch that before impacting the rest.

**Comment by kaosat-dev** [comment]
@CalobHumble could you please update your project with the latest version of the @jscad modules ? 
It should now be fixed: I tested your script locally and it now works fine for me.

**Comment by calob-dev** [comment]
@kaosat-dev sorry about the long wait.  But yes, with the new modules, everything works just as expected.
